name: Java Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Run Tests
        run: |
          sudo apt-get update
          sudo apt-get install openjdk-11-jdk
          curl -L -o ideaIC.tar.gz "https://download.jetbrains.com/idea/ideaIC-2021.3.tar.gz"
          tar -xzf ideaIC.tar.gz
          ./idea-IC-*/bin/idea.sh test
