name: Java Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '20.0.1'
          distribution: 'jdk'
          architecture: 'x64'
          check-latest: false
          server-id: 'github'
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Run Tests
        run: |
          sudo apt-get update
          sudo apt-get install openjdk-20-jdk
          curl -L -o ideaIC.tar.gz "https://download.jetbrains.com/idea/ideaIC-2023.1.3.tar.gz"
          tar -xzf ideaIC.tar.gz
          ./idea-IC-*/bin/idea.sh test
